//! HTTP route modules. Each exposes a `pub fn router() -> Router<AppState>`.

pub mod achievements;
pub mod admin;
pub mod admin_panel;
pub mod api_tokens;
pub mod auth;
pub mod backups;
pub mod boards;
pub mod dashboards;
pub mod fields;
pub mod health;
pub mod integrations;
pub mod labels;
pub mod metrics;
pub mod notifications;
pub mod payroll;
pub mod projects;
pub mod retros;
pub mod search;
pub mod sprints;
pub mod task_detail;
pub mod tasks;
pub mod time_logs;
pub mod timesheets;
pub mod users;
pub mod vault;
pub mod webhooks;
pub mod ws;
